name: Test version bump

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.github/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check version file was changed if there are code changes
      run: |
        git fetch origin master
        git --no-pager diff --name-only origin/master | grep version.rb
